## 数据库配置##
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/gkemr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    password: root
  thymeleaf:
    cache: false
    enabled: false
  mvc:
    view:
      prefix: /WebRoot/html/
      suffix: .jsp
server:
  port: 8888

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.slwh.emr.model

## log4j配置##

logging:
       level:
         com.slwh.emr.mapper: DEBUG
##shiro配置
jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect